#
# Module manifest for module 'PoShAdmin'
#
# Generated by: Greg Szabo
#
# Generated on: 2016-01-21
#

@{

# Script module or binary module file associated with this manifest.
# Not compatible with PowerShell 2.0
#RootModule = 'PoShAdmin.DLL'

# Version number of this module.
ModuleVersion = '1.1'

# ID used to uniquely identify this module
GUID = 'e03541ba-42b3-4de5-b8d8-b3907850420c'

# Author of this module
Author = 'Greg Szabo'

# Company or vendor of this module
CompanyName = 'PoShAdmin.Net'

# Copyright statement for this module
Copyright = '(c) 2016 PoShAdmin.Net. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PoShAdmin.Net Advanced SysAdmin Functionality for PowerShell'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = '2.0'

# Minimum version of the common language runtime (CLR) required by this module
# For PowerShell 2.0:
CLRVersion = '2.0.50727.5420'
# For PowerShell 5.0
# CLRVersion = '4.0.30319.42000'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @("PoShAdmin.DLL")

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @("PoShAdmin.format.ps1xml")

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @("PoShAdmin.psm1","PoShAdmin.DLL")

# Functions to export from this module
FunctionsToExport = @('*-PoSh*','Get-ComputerName')

# Cmdlets to export from this module
CmdletsToExport = '*-PQ*'

# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module
# AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

